using MyQuizGenerator.Application.Common.Interfaces;
using MyQuizGenerator.Application.Decks.DTOs;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace MyQuizGenerator.Infrastructure.Services;

public class PdfService : IPdfService
{
    public byte[] GenerateDeckPdf(DeckDetailResponse deck)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(28);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Content().Column(column =>
                {
                    RenderHeader(column, deck);
                    column.Item().PaddingTop(8).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                    RenderQuestions(column, deck);
                });

                page.Footer()
                    .AlignCenter()
                    .DefaultTextStyle(x => x.FontSize(9).FontColor(Colors.Grey.Darken1))
                    .Text(text =>
                    {
                        text.Span("Generated by MyQuiz - ");
                        text.CurrentPageNumber();
                        text.Span(" / ");
                        text.TotalPages();
                    });
            });
        });

        return document.GeneratePdf();
    }

    public string BuildSafeFileName(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            return "deck";
        }

        var invalidChars = Path.GetInvalidFileNameChars();
        var sanitized = new string(name.Select(ch => invalidChars.Contains(ch) ? '_' : ch).ToArray());
        return string.IsNullOrWhiteSpace(sanitized) ? "deck" : sanitized.Trim();
    }

    private static void RenderHeader(ColumnDescriptor column, DeckDetailResponse deck)
    {
        column.Item().Text(deck.Name).FontSize(20).Bold();

        if (!string.IsNullOrWhiteSpace(deck.Description))
        {
            column.Item().PaddingTop(6).Text(deck.Description).FontSize(12).FontColor(Colors.Grey.Darken2);
        }

        column.Item().PaddingTop(8).Text($"Questions: {deck.QuestionCount} | Owner: {deck.OwnerName} ({deck.OwnerEmail})")
            .FontSize(10)
            .FontColor(Colors.Grey.Darken1);
    }

    private static void RenderQuestions(ColumnDescriptor column, DeckDetailResponse deck)
    {
        for (var i = 0; i < deck.Questions.Count; i++)
        {
            var question = deck.Questions[i];

            column.Item().PaddingBottom(12).Column(q =>
            {
                q.Item().Text($"{i + 1}. {question.Content}").Bold();
                q.Item().Text($"Type: {question.Type}").FontSize(10).FontColor(Colors.Grey.Darken1);

                RenderOptions(q, question);
                RenderCorrectAnswers(q, question);
                RenderHint(q, question);
                RenderExplanation(q, question);
            });
        }
    }

    private static void RenderOptions(ColumnDescriptor q, QuestionResponse question)
    {
        if (question.Options.Length == 0) return;

        q.Item().PaddingTop(4).Column(options =>
        {
            for (var i = 0; i < question.Options.Length; i++)
            {
                options.Item().Text($"{GetOptionLabel(i)}) {question.Options[i]}");
            }
        });
    }

    private static void RenderCorrectAnswers(ColumnDescriptor q, QuestionResponse question)
    {
        if (question.CorrectAnswers.Length == 0) return;

        q.Item().PaddingTop(4)
            .Text($"Correct answer(s): {string.Join(", ", question.CorrectAnswers)}")
            .FontColor(Colors.Green.Darken2);
    }

    private static void RenderHint(ColumnDescriptor q, QuestionResponse question)
    {
        if (string.IsNullOrWhiteSpace(question.Hint)) return;

        q.Item().PaddingTop(2).Text($"Hint: {question.Hint}").FontColor(Colors.Orange.Darken2);
    }

    private static void RenderExplanation(ColumnDescriptor q, QuestionResponse question)
    {
        if (string.IsNullOrWhiteSpace(question.Explanation)) return;

        q.Item().PaddingTop(2).Text($"Explanation: {question.Explanation}").FontColor(Colors.Blue.Darken2);
    }

    private static string GetOptionLabel(int index)
    {
        return ((char)('A' + (index % 26))).ToString();
    }
}
